FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies and Java 8
RUN apt-get update && apt-get install -y \
    openjdk-8-jdk \
    curl \
    wget \
    gnupg \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Set Java environment
#ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd4
#ENV PATH=$JAVA_HOME/bin:$PATH

# Install Maven
RUN apt-get update && apt-get install -y maven
RUN readlink -f /usr/bin/java

# Install git
RUN apt-get update && apt-get install -y git
# Set Maven environment variables
#ENV MAVEN_HOME=/opt/apache-maven-3.9.8
#ENV PATH=$MAVEN_HOME/bin:$PATH

# Verify both work
RUN java -version
RUN mvn -version

RUN apt-get update && apt-get install -y build-essential

RUN wget https://github.com/albertogoffi/toradocu/archive/refs/tags/v3.0.zip
RUN apt-get install -y unzip
RUN unzip v3.0.zip
RUN mv /toradocu-3.0 /toradocu
WORKDIR /toradocu

RUN ./gradlew shadowJar -Dhttp.socketTimeout=50000 -Dhttp.connectionTimeout=50000

# Add a build argument for cache busting
ARG CACHEBUST=1
# Copy config files
#COPY Toradocu.java /toradocu/src/main/java/org/toradocu
#COPY JsonOutputSerializer.java /toradocu/src/main/java/org/toradocu/output/util
COPY GsonInstance.java /toradocu/src/main/java/org/toradocu/util
RUN ./gradlew clean shadowJar --offline
WORKDIR /app
CMD ["bash"]
