[config]
#use litellm provider
#https://docs.litellm.ai/docs/providers
#model = "ollama/llama3.3:70b"

#or use openai compatible endpoint
#https://docs.litellm.ai/docs/providers/openai_compatible
#model = "openai/llama3.3:70b"
#LITELLM_API_BASE = "http://localhost:11434/v1"

model = "openai/deepseek-ai/deepseek-coder-33b-instruct"
LITELLM_API_BASE = "http://localhost:8010/v1"

[translation]
iteration_repairloop = 5
