import click
from pathlib import Path
from llmedico.main import main as run_pipeline

@click.command(name="translate")
@click.option(
    "--target-class",
    "fq_class_name",
    required=True,
    help="Fully qualified class name, e.g. 'org.project.MyClass'",
)
@click.option(
    "--target-method",
    "target_method",
    required=False,
    default=None,
    help="DEBUG ONLY: Method of class for which the tool has to translate conditions",
)
@click.option(
    "--src-dir",
    "path_src_dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    required=True,
    help="Directory containing all the source files of the project. e.g. /data/input/project/src/",
)

@click.option("--jar-dir", "path_jar_dir",
              type=click.Path(),
              help="The project compiled as a jar. _e.g. /data/input/project/target/project.jar")
@click.option(
    "--out-dir",
    "path_output_dir",
    type=click.Path(file_okay=False, path_type=Path),
    required=True,
    help="Directory to save every file generated by LLMedico.",
)

def translate_command(fq_class_name, target_method, path_src_dir, path_jar_dir, path_output_dir):
    """
    Translate a Java class and generate conditions.
    """

    click.echo("=== LLMedico: analyze ===")
    click.echo(f"Target class:   {fq_class_name}")
    click.echo(f"Target method:  {target_method}")
    click.echo(f"Source dir:     {path_src_dir}")
    click.echo(f"Jar dir:     {path_jar_dir}")
    click.echo(f"Output dir:     {path_output_dir}")

    run_pipeline(fq_class_name=fq_class_name,
                 target_method=target_method,
                 path_source_dir=path_src_dir,
                 path_output_dir=path_output_dir,
                 path_jar=path_jar_dir)

